### ISSUE TITLE
Can you trouble the big guy to also provide AML RTL8822BS drivers?

### ISSUE THREAD

**Issue by nano-oss** [CoreELEC/RTL8852BE-aml#1]
My machine is cm201-1-ys, the cpu model is s905L3B, the network card model is: RTL8822BS, there is no way to use the wireless network card after swiping the latest version of armbian, if you want to trouble the big guy, you can also provide the network card driver of this model? Thank you very much, excuse me!

我的机器是cm201-1-ys，cpu型号是s905L3B，网卡型号是：RTL8822BS，刷了最新版本的armbian都没有办法使用无线网卡，想麻烦大佬有空的话也提供一下这个型号的网卡驱动可以吗？十分感谢，打扰了！

**Comment by vpeter4** [comment]
We don't have crystal ball to guess what is wrong.
